[2025-02-19T13:36:08.203+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/covid.py
[2025-02-19T13:36:08.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T13:36:08.205+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:36:08.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T13:36:09.369+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:36:09.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T13:36:09.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T13:36:09.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.187 seconds
[2025-02-19T13:36:39.536+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/covid.py
[2025-02-19T13:36:39.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T13:36:39.538+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:36:39.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T13:36:39.920+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:36:39.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T13:36:39.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T13:36:39.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.403 seconds
[2025-02-19T13:37:10.092+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/covid.py
[2025-02-19T13:37:10.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T13:37:10.094+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:37:10.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T13:37:10.467+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:37:10.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T13:37:10.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T13:37:10.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.393 seconds
[2025-02-19T13:37:40.644+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/covid.py
[2025-02-19T13:37:40.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T13:37:40.648+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:37:40.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T13:37:41.041+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:37:41.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T13:37:41.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T13:37:41.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.418 seconds
[2025-02-19T13:38:11.228+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/covid.py
[2025-02-19T13:38:11.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T13:38:11.230+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:38:11.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T13:38:11.632+0000] {logging_mixin.py:190} INFO - [2025-02-19T13:38:11.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T13:38:11.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T13:38:11.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.423 seconds
[2025-02-19T14:48:39.184+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:48:39.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:48:39.187+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:48:39.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:48:40.763+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:48:40.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T14:48:40.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:48:40.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.600 seconds
[2025-02-19T14:49:10.958+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:49:10.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:49:10.961+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:49:10.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:49:11.371+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:49:11.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/covid.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/covid.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-02-19T14:49:11.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:49:11.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.434 seconds
[2025-02-19T14:54:57.472+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:54:57.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:54:57.474+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:54:57.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:54:58.928+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:54:58.927+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-02-19T14:54:59.988+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/covid.py:7 DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-02-19T14:54:59.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:55:00.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 2.542 seconds
[2025-02-19T14:55:30.198+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:55:30.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:55:30.200+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:55:30.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:55:31.525+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/covid.py:7 DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-02-19T14:55:31.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:55:31.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.346 seconds
[2025-02-19T14:55:35.232+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:55:35.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:55:35.234+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:55:35.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:55:36.539+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/covid.py:7 DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-02-19T14:55:36.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:55:36.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.323 seconds
[2025-02-19T14:56:06.719+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:56:06.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:56:06.722+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:06.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:56:08.046+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/covid.py:7 DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-02-19T14:56:08.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:56:08.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.349 seconds
[2025-02-19T14:56:22.166+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:56:22.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:56:22.169+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:22.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:56:23.593+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/covid.py:7 DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-02-19T14:56:23.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:56:23.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 1.451 seconds
[2025-02-19T14:56:53.797+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:56:53.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:56:53.800+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:53.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:56:53.805+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:53.804+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/covid.py assumed to contain no DAGs. Skipping.
[2025-02-19T14:56:53.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:56:53.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.022 seconds
[2025-02-19T14:56:55.814+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:56:55.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:56:55.817+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:55.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:56:55.821+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:56:55.821+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/covid.py assumed to contain no DAGs. Skipping.
[2025-02-19T14:56:55.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:56:55.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.020 seconds
[2025-02-19T14:57:26.001+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/covid.py
[2025-02-19T14:57:26.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/covid.py for tasks to queue
[2025-02-19T14:57:26.004+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:57:26.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/covid.py
[2025-02-19T14:57:26.008+0000] {logging_mixin.py:190} INFO - [2025-02-19T14:57:26.008+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/covid.py assumed to contain no DAGs. Skipping.
[2025-02-19T14:57:26.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/covid.py
[2025-02-19T14:57:26.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/covid.py took 0.023 seconds
